### ISSUE TITLE
Equivalent Java Log Parser

### ISSUE THREAD

**Issue by kaidul** [githoov/spark_log_data#1]
Hi Scott Hoover,

I've wrote a similar project on Java covering all features as you + some additional features like check-pointing, write-ahead-logging, persisting in memory and/or disk etc. I've already tested the project. Instead of pushing as a new project, I would like to contribute on this project.

Please let me know what you're thinking.

Regards,
Kaidul

**Comment by githoov** [comment]
@kaidul That'd be great! Now, as you can see, I haven't really done much here since the original work. This was largely an effort to make a public example of a webinar I gave while at Looker. With that said, if this is something you want to contribute to, I'm more than happy to maintain this project.

**Comment by kaidul** [comment]
@githoov I am very glad for having your approval :) I am going to fork your project and will send you the pull request.
